//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int id { get; set; }
        public Nullable<int> roomNumber { get; set; }
        public Nullable<int> accID { get; set; }
        public Nullable<int> roomTypeID { get; set; }
        public Nullable<int> catID { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Accomodation Accomodation { get; set; }
        public virtual Category Category { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
